# Generated by Django 6.0.7 on 2026-08-13 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Downtown Condo', max_length=200)),
                ('property_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('LAND', 'Land'), ('VACATION', 'Vacation Home'), ('OTHER', 'Other')], default='RESIDENTIAL', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monthly_rental_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_operating_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('has_mortgage', models.BooleanField(default=False)),
                ('mortgage_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mortgage_interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mortgage_monthly_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
