# Generated by Django 4.2.28 on 2026-07-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_type',
            field=models.CharField(choices=[('monthly', 'Monthly Fixed'), ('daily', 'Daily Allocation'), ('rolling', 'Rolling/Carryover'), ('department', 'Department/Project')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='budget',
            name='carryover_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount carried over from previous period', max_digits=12),
        ),
        migrations.AddField(
            model_name='budget',
            name='department_name',
            field=models.CharField(blank=True, help_text='Used only for department budgets', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='Was this budget baseline suggested by AI?'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, help_text='Total overarching budget', max_digits=12),
        ),
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to='budget.budget')),
            ],
        ),
    ]
