# Generated by Django 6.0.7 on 2026-08-13 09:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FIREProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_withdrawal_rate', models.DecimalField(decimal_places=2, default=Decimal('4.00'), help_text='e.g., 4.00 for 4% rule', max_digits=5)),
                ('expected_investment_return', models.DecimalField(decimal_places=2, default=Decimal('7.00'), help_text='Real return after inflation, e.g., 7.00 for 7%', max_digits=5)),
                ('inflation_rate', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='e.g., 3.00 for 3%', max_digits=5)),
                ('current_age', models.IntegerField(default=30)),
                ('target_retirement_age', models.IntegerField(default=50)),
                ('manual_annual_income', models.DecimalField(blank=True, decimal_places=2, help_text='Override system calculated income', max_digits=15, null=True)),
                ('manual_annual_expenses', models.DecimalField(blank=True, decimal_places=2, help_text='Override system calculated expenses', max_digits=15, null=True)),
                ('manual_current_net_worth', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('manual_investment_portfolio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('selected_scenario', models.CharField(choices=[('lean', 'Lean FIRE (Minimal Lifestyle)'), ('regular', 'Regular FIRE (Current Lifestyle)'), ('fat', 'Fat FIRE (Luxury Lifestyle)'), ('coast', 'Coast FIRE (No more contributions needed)'), ('barista', 'Barista FIRE (Part-time work in retirement)')], default='regular', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fire_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FIRESimulationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_fire_number', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('years_to_fire', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('projected_fire_date', models.DateField(blank=True, null=True)),
                ('current_savings_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('timeline_data', models.TextField(blank=True, default='[]', help_text='JSON serialized timeline progression')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fire_simulation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
