# Generated by Django 4.2.28 on 2026-07-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialgoal',
            name='expected_inflation_rate',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='Annual inflation %', max_digits=5),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='expected_return_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Expected annual return on investments %', max_digits=5),
        ),
    ]
