# Generated by Django 6.0.7 on 2026-07-14 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_name', models.CharField(max_length=200)),
                ('investment_type', models.CharField(choices=[('mutual_fund', 'Mutual Fund'), ('fd', 'Fixed Deposit'), ('sip', 'SIP'), ('ppf', 'PPF'), ('nps', 'NPS'), ('gold', 'Gold'), ('silver', 'Silver'), ('real_estate', 'Real Estate'), ('govt_scheme', 'Government Scheme'), ('bond', 'Bond'), ('etf', 'ETF'), ('other', 'Other')], max_length=30)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('purchase_date', models.DateField()),
                ('broker', models.CharField(blank=True, max_length=150, null=True)),
                ('annual_return', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
