# Generated by Django 4.2.28 on 2026-07-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='risk_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='sector',
            field=models.CharField(blank=True, help_text='e.g., Technology, Healthcare, Real Estate', max_length=100, null=True),
        ),
    ]
