# Generated by Django 6.0.7 on 2026-07-14 04:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=150)),
                ('bank', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('savings', 'Savings Account'), ('fd', 'Fixed Deposit'), ('rd', 'Recurring Deposit'), ('ppf', 'PPF'), ('nps', 'NPS'), ('emergency', 'Emergency Fund'), ('other', 'Other')], default='savings', max_length=30)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('goal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('goal_deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='savings.savingsaccount')),
            ],
        ),
    ]
