# Generated by Django 4.2.28 on 2026-07-14 07:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., USD, INR, EUR', max_length=3, unique=True)),
                ('name', models.CharField(help_text='e.g., US Dollar', max_length=50)),
                ('symbol', models.CharField(help_text='e.g., $, ₹, €', max_length=10)),
                ('is_base', models.BooleanField(default=False, help_text='Set to True for your primary currency')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, help_text='Multiplier to convert from_currency to to_currency', max_digits=18)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_manual', models.BooleanField(default=False, help_text='True if rate was manually overridden')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates_from', to='currency.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates_to', to='currency.currency')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
    ]
