# Generated by Django 4.2.28 on 2026-07-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='ocr_processed',
            field=models.BooleanField(default=False, help_text='Has this receipt been processed by the OCR engine?'),
        ),
        migrations.AddField(
            model_name='expense',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Raw text extracted from OCR', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
