# Generated by Django 4.2.28 on 2026-07-14 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('trend_period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('average_spend', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_spend', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category', 'trend_period')},
            },
        ),
        migrations.CreateModel(
            name='CashFlowForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('expected_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ai_confidence_score', models.IntegerField(default=80, help_text='AI confidence % in this forecast')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_forecasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['forecast_date'],
                'unique_together': {('user', 'forecast_date')},
            },
        ),
    ]
