# Generated by Django 4.2.28 on 2026-07-14 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('employer', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('annual_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('other_income_sources', models.TextField(blank=True, help_text='List other income sources (e.g., Freelancing, Rental)', null=True)),
                ('country', models.CharField(blank=True, default='India', max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(default='INR', help_text='Base currency for reports', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('risk_appetite', models.CharField(choices=[('Low', 'Low Risk - Capital Preservation'), ('Medium', 'Medium Risk - Balanced Growth'), ('High', 'High Risk - Aggressive Growth')], default='Medium', max_length=20)),
                ('investment_experience', models.CharField(choices=[('Beginner', 'Beginner (< 2 years)'), ('Intermediate', 'Intermediate (2-5 years)'), ('Expert', 'Expert (5+ years)')], default='Beginner', max_length=20)),
                ('preferred_investment_types', models.TextField(blank=True, help_text='e.g., Stocks, Mutual Funds, Real Estate', null=True)),
                ('preferred_banks', models.TextField(blank=True, help_text='Preferred banking partners', null=True)),
                ('retirement_age', models.IntegerField(default=60)),
                ('number_of_dependents', models.IntegerField(default=0)),
                ('financial_goals', models.TextField(blank=True, help_text='High-level goals (e.g., Buy a house, Retire early)', null=True)),
                ('monthly_savings_target', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('emergency_fund_target', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('nominee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nominee_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
