# Generated by Django 4.2.28 on 2026-08-03 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bank', 'Bank Account'), ('card', 'Card')], default='bank', max_length=20)),
                ('account_type', models.CharField(choices=[('savings', 'Savings Account'), ('current', 'Current Account'), ('salary', 'Salary Account'), ('joint', 'Joint Account'), ('fixed_deposit', 'Fixed Deposit'), ('recurring_deposit', 'Recurring Deposit'), ('credit', 'Credit Card'), ('debit', 'Debit Card'), ('prepaid', 'Prepaid Card'), ('virtual', 'Virtual Card'), ('forex', 'Forex Card'), ('utility', 'Utility / Stored Value Card'), ('other', 'Other')], default='savings', max_length=30)),
                ('provider', models.CharField(help_text='Bank or Provider Name', max_length=150)),
                ('nickname', models.CharField(blank=True, max_length=150, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('rewards_program', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('custom_icon', models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50, null=True)),
                ('theme_color', models.CharField(blank=True, help_text='Hex color code', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('interest_type', models.CharField(choices=[('simple', 'Simple Interest'), ('compound', 'Compound Interest')], default='simple', max_length=20)),
                ('compounding_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('annually', 'Annually'), ('at_maturity', 'At Maturity')], max_length=20, null=True)),
                ('interest_credit_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('annually', 'Annually'), ('at_maturity', 'At Maturity')], max_length=20, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0, help_text='Tax withholding %', max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('salary', 'Salary'), ('bonus', 'Bonus'), ('cash_deposit', 'Cash Deposit'), ('interest', 'Interest Credit'), ('refund', 'Refund'), ('investment_return', 'Investment Return'), ('cashback', 'Cashback'), ('rewards', 'Rewards'), ('expense', 'Expense'), ('purchase', 'Purchase'), ('bill', 'Bill Payment'), ('atm', 'ATM Withdrawal'), ('fee', 'Bank Charges'), ('emi', 'EMI'), ('tax', 'Taxes'), ('subscription', 'Subscription'), ('loan_repayment', 'Loan Repayment'), ('transfer', 'Transfer'), ('internal', 'Internal Transfer'), ('wallet', 'Wallet Transfer'), ('upi', 'UPI'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('imps', 'IMPS'), ('wire', 'Wire Transfer'), ('adjustment_credit', 'Balance Correction (Credit)'), ('adjustment_debit', 'Balance Correction (Debit)'), ('reversal', 'Reversal'), ('chargeback', 'Chargeback')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.account')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banktransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='user',
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
