# Generated by Django 4.2.28 on 2026-08-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_account_banktransaction_remove_creditcard_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='interest_accrued',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
