# Generated by Django 4.2.28 on 2026-07-14 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('identity', 'Identity (PAN/Aadhar/SSN)'), ('passport', 'Passport'), ('property', 'Property Deed'), ('vehicle', 'Vehicle RC/Title'), ('tax', 'Tax Return'), ('insurance', 'Insurance Policy'), ('other', 'Other')], default='other', max_length=20)),
                ('file_path', models.FileField(upload_to='secure_documents/')),
                ('is_encrypted', models.BooleanField(default=True, help_text='Indicates if the file is encrypted at rest')),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
