# Generated by Django 6.0.7 on 2026-07-14 04:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=200)),
                ('loan_type', models.CharField(choices=[('home', 'Home Loan'), ('vehicle', 'Vehicle Loan'), ('education', 'Education Loan'), ('gold', 'Gold Loan'), ('personal', 'Personal Loan'), ('business', 'Business Loan'), ('other', 'Other')], max_length=20)),
                ('lender', models.CharField(max_length=150)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('emi_date', models.IntegerField(default=1, help_text='Day of month EMI is due')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
