# Generated by Django 4.2.28 on 2026-07-14 07:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('home', 'Home Loan'), ('vehicle', 'Vehicle Loan'), ('education', 'Education Loan'), ('gold', 'Gold Loan'), ('personal', 'Personal Loan'), ('business', 'Business Loan'), ('bnpl', 'Buy Now Pay Later'), ('cc_emi', 'Credit Card EMI'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('principal_component', models.DecimalField(decimal_places=2, default=0, help_text='Amount going towards principal', max_digits=12)),
                ('interest_component', models.DecimalField(decimal_places=2, default=0, help_text='Amount going towards interest', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
