# Generated by Django 4.2.28 on 2026-07-14 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wealth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_age', models.IntegerField(default=30)),
                ('retirement_age', models.IntegerField(default=60)),
                ('life_expectancy', models.IntegerField(default=85)),
                ('current_monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_inflation_rate', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('expected_return_rate_pre_retirement', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('expected_return_rate_post_retirement', models.DecimalField(decimal_places=2, default=7.0, max_digits=5)),
                ('existing_retirement_corpus', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retirement_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyFundPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months_to_cover', models.IntegerField(default=6, help_text='Number of months of expenses to save')),
                ('current_monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_saved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_fund_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
