# Generated by Django 6.0.7 on 2026-08-13 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Freelance Consulting, Etsy Shop', max_length=200)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income (Revenue)'), ('EXPENSE', 'Expense (Cost)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('client_or_vendor', models.CharField(blank=True, help_text='Who paid you or who you paid', max_length=200, null=True)),
                ('is_tax_deductible', models.BooleanField(default=False, help_text='Can this expense be deducted?')),
                ('tax_category', models.CharField(blank=True, help_text='e.g. Software, Travel, Meals', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='business_ledger.businessprofile')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
