# Generated by Django 4.2.28 on 2026-07-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoholding',
            name='category',
            field=models.CharField(blank=True, help_text='e.g., Layer 1, DeFi, Meme', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cryptoholding',
            name='risk_level',
            field=models.CharField(choices=[('Medium', 'Medium'), ('High', 'High'), ('Extreme', 'Extreme')], default='High', max_length=20),
        ),
    ]
