# Generated by Django 6.0.7 on 2026-07-14 04:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('stock_symbol', models.CharField(max_length=20)),
                ('exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE'), ('NYSE', 'NYSE'), ('NASDAQ', 'NASDAQ'), ('OTHER', 'Other')], default='NSE', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
